### ISSUE TITLE
get_dfa, get_dfq, get_dfm methods refactoring

### ISSUE THREAD

**Issue by varnie** [epogrebnyak/mini-kep#14]
В классе Frame есть методы get_dfa, get_dfq, get_dfm. 

Выродилось из комментария в коде:
> TO DISCUSS: get_df*() creates data every time we call them,
>              may create self.dfa, etc and return.

Предлагается создавать по требованию 1 раз, далее возвращать уже созданный инстанс.

**Comment by epogrebnyak** [comment]
Fixed by 027a92a44f345b6d2c36fca1acde549ce6b9cdf6. 

df* is an instance attribute now
