### ISSUE TITLE
online coverage badge 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#23]
<https://codecov.io/gh/epogrebnyak/mini-kep> or coveralls
<https://github.com/epogrebnyak/mini-kep/blob/master/.travis.yml#L11-L12>

Need step-by-step procedure resulting in coverage badge in README.md.

**Comment by epogrebnyak** [comment]
Не получается поставить бэдж покрытия кода тестами. Идеологию понимаю - нужно сгенерить 
   через coverage.py данные, подключить его к coveralls.io или codecov.io

Ошибки:
- coveralls.io - не видит части моих репозитариев
- codecov.io - один раз прогнал тесты и завис

   
Не ясно:
 - coverage должен запускаться локально или в ходе тестирвания Travis-CI? (видимо в Travis-CI)  
 - coverage должен запускаться в составе py.test и не охватывать сами тесты test_*.py 
 - основной код в данном проекте в папке src/kep - где находится сам файл с coverage? в корне?
 - coverage должен запускаться самостоятельно или в состове pytest?

**Comment by php-coder** [comment]
> coverage должен запускаться локально или в ходе тестирвания Travis-CI? (видимо в Travis-CI)

Для любого их этих сервисов не важно откуда эти данные пришли (локально вы их собрали или на CI) так они всего лишь отображают данные.

**Comment by epogrebnyak** [comment]
У меня codecov.io завис на коммите дня 21 назад и больше коммитов не хочет видеть. Насколько Travis-CI понятная система, настолько codecov.io непонятная. (

**Comment by epogrebnyak** [comment]
Seems to work: now we have [this stat](https://codecov.io/gh/epogrebnyak/mini-kep/tree/master/src) to check coverage in src!
