### ISSUE TITLE
Inaccurate/misleading exception message in RowStack/pop

### ISSUE THREAD

**Issue by varnie** [epogrebnyak/mini-kep#27]
Речь про строки:

```
elif not s or not e:
    raise ValueError("Single None as a marker cannot be processed")
```

в методе pop класса RowStack.

в случаях:
1)
marker['start'] явл. пустой строкой, т.е ""
marker['end'] явл. строкой "abc"
2) 
marker['end'] явл. пустой строкой, т.е ""
marker['start'] явл. строкой "abc"

получим мутное сообщение эксепшна, что якобы был задан 1 **None**, хотя это не так (пустая строка - это не None).

**Comment by epogrebnyak** [comment]
- Changed error reporting at cfg.Scope() near <https://github.com/epogrebnyak/mini-kep/blob/master/src/kep/cfg.py#58>
- Empty boundaries (start or end) not permitted
