### ISSUE TITLE
Move assertions from modules to test modules

### ISSUE THREAD

**Issue by varnie** [epogrebnyak/mini-kep#32]
Предлагаю перенести все проверки из модуля cfg ко всем остальным проверкам модуля cfg, в файл test_cfg.py, если нет возражений.
Аналогично для модуля tables, перенести в test_tables.py.

**Comment by epogrebnyak** [comment]
- Предлагаю оставить - assert в cfg.py имеют функцию валидации, а не тестирования алгоритма, они должны выполняться даже без запуска тестов, их смысл - показать, что если что-то поменяли в определениях, то надо поменять и в других константах. В test_cfg.py не переносить. 
- В tables я не вижу валидаций и assert'ов сейчас, там вроде бы нечего переносить.

**Comment by varnie** [comment]
Куда делся "test_csv_has_no_null_byte"?

**Comment by epogrebnyak** [comment]
подзатер - надо восстановить из ветки ```before_simplify```, можно в отдельный файл test_misc.py
