### ISSUE TITLE
document and refactor kep.spec

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#38]
See list of todos in [readme](https://github.com/epogrebnyak/mini-kep#1-current-stable-version-in-master-branch).

Files:
- html: <http://mini-kep-docs.s3-website-eu-west-1.amazonaws.com/kep.spec.html>
- code: <https://github.com/epogrebnyak/mini-kep/blob/master/src/kep/spec.py>
- test: <https://github.com/epogrebnyak/mini-kep/blob/master/src/kep/tests/test_spec.py>
- rst: <https://github.com/epogrebnyak/mini-kep/blob/master/doc/kep.files.rst>

**Comment by epogrebnyak** [comment]
- [ ] Extract usage **SPEC** and **UNIT** from **tables.py**

**Comment by epogrebnyak** [comment]
Refacroring proposal: we have too many append methods in Definition/Scope, Scopes are added to Specification. Better logic is: 
- init Scope
- init Definition with Scope and reader
- make Specification a collection of Definitions (not Scopes)

This also makes **append()** methods simplier.

Tentative call:

```python
# change 1 - init of Definition
main = Definition(varname="GDP",
            text=["Oбъем ВВП",
                  "Индекс физического объема произведенного ВВП, в %",
                  "Валовой внутренний продукт"],
            required_units=["bln_rub", "yoy"],
            desc="Валовый внутренний продукт (ВВП)",
            sample="1999	4823	901	1102	1373	1447")
SPEC = Specification(main)
sc = Scope(start="3.5. Индекс потребительских цен",
           end="4. Социальная сфера")
# change 2 - method name
sc.append(start="4.5. Индекс потребительских цен",
           end="5. Социальная сфера")           
# change 3 - init and composition
d = Definition(sc, reader = None)
d.append("CPI",
          text="Индекс потребительских цен",
          required_units="rog",
          desc="Индекс потребительских цен (ИПЦ)")
d.append("CPI_NONFOOD",
          text=["непродовольственные товары",
                "непродовольст- венные товары"],
          required_units="rog",
          desc="ИПЦ (непродтовары)")
# change 4 - some methods will be depreciated
# change 5 - other changes needed?
SPEC.append(sc)
# change 6 - is access from outside unaffected?
```

**Comment by bakakaldsas** [comment]
_UNITS_ usage in rows.py
`
import kep.spec as spec
...
class Row:
...
    def get_unit(self, units_mapper_dict=spec.UNITS):
        for k in units_mapper_dict.keys():
            if k in self.name:
                return units_mapper_dict[k]
        return False
`

**Comment by bakakaldsas** [comment]
_UNITS_ usage in _tables.py_
Import:
```
from kep.spec import UNITS
```
In:
```
class Tables:
    def __init__(self, _rows, spec=SPEC, units=UNITS):
...
        self.units = units
...
```
Later used in as _self.units_:
```
    def yield_tables(self):
        for csv_segment, pdef in self.to_parse:
            for t in self.extract_tables(csv_segment, pdef, self.units):
                yield t
```
passed to as _units_dict_:
```
    @staticmethod
    def extract_tables(csv_segment, pdef, units_dict):
        # yield tables from csv_segment
        tables = split_to_tables(csv_segment)
        # parse tables to obtain labels
        varnames_dict = pdef.headers
        tables = [t.set_label(varnames_dict, units_dict) for t in tables]
        tables = [t.set_splitter(pdef.reader) for t in tables]
        # another run to assign trailing units to some tables
        fix_multitable_units(tables)
        # were all required tables read?
        labels_missed = missed_labels(tables, pdef.required)
        if labels_missed:
            raise ValueError("Missed labels: {}".format(labels_missed))
        return tables
```
In:
```
class Table:
```
In method _parse_ as _units_dict_ however I didn't find any call to it.
```
    def parse(self, varnames_dict, units_dict, funcname):
        self.set_label(varnames_dict, units_dict)
        self.set_splitter(funcname)
        return self
```
In method _set_label_ as _units_dict_:
```
    def set_label(self, varnames_dict, units_dict):
        for row in self.headers:
            varname = row.get_varname(varnames_dict)
            if varname:
                self.varname = varname
                self.lines[row.name] = self.KNOWN
            unit = row.get_unit(units_dict)
            if unit:
                self.unit = unit
                self.lines[row.name] = self.KNOWN
        return self
```

**Comment by bakakaldsas** [comment]
_SPEC_ usege in _tables.py_
Import:
```
from kep.spec import SPEC
```
In:
```
class Tables:
...
    def __init__(self, _rows, **spec=SPEC**, units=UNITS):
        self.rowstack = RowStack(_rows)
        **self.spec** = **spec**
        self.units = units
        self.required = [make_label(varname, unit)
                         for varname, unit in **spec.required()**]
        self.make_queue()

    def make_queue(self):
...
        self.to_parse = []
        for **scope** in **self.spec.scopes**:
            # find segemnt limits
            start, end = **scope.get_bounds(self.rowstack.rows)**
            # pop csv segment
            csv_segment = self.rowstack.pop(start, end)
            # get current parsing definition
            pdef = **scope.get_parsing_definition()**
            self.to_parse.append([csv_segment, pdef])
        csv_segment = self.rowstack.remaining_rows()
        pdef = **self.spec.get_main_parsing_definition()**
        self.to_parse.append([csv_segment, pdef])


```

**Comment by epogrebnyak** [comment]
Thanks for extracting the calls, it is very useful perspective.

**Comment by epogrebnyak** [comment]
New spec.py classes are [here](https://github.com/epogrebnyak/mini-kep/commit/21e6186b0c9fc8c3b7036f8e5eac5df89f82dd8e):
- [ ] restore usage in tables.py - existing tests should pass
- [ ] docstrings editing
- [ ] write asserts/tests 
- [ ] convert existing definition
- [ ] list of PROPOSALs marked in text

**Comment by epogrebnyak** [comment]
Deprieciated, here we do not needa global default

_UNITS_ usage in _tables.py_
Import:
```
from kep.spec import UNITS
```

**Comment by epogrebnyak** [comment]
@bakakaldsas, most review for spec.py done, can close after you approve

Remaining todos (not todo now):

- [ ] # TODO: add more definitons
- [ ] # TODO: transformations layer diff GOV_ACCUM
- [ ] # TODO: use sample in required
- [ ] # TODO: short names for variables in FRED style, short=

**Comment by epogrebnyak** [comment]
Replaces #22 and #15.

Finished review, proceeding to #52. 

Job description saved in <https://github.com/epogrebnyak/mini-kep/edit/master/todo_refactoring.md> and also below:

Intent: document and test current stable version (found in *master* branch)

By module do:
 - (optional) propose/discuss/commit/eye review changes to code  
 - write assert statements and edit/enhance tests
 - edit module docstrings:
   - module
   - classes, public methods and functions used in other parts of the program
   - other docstrings/comments where needed
 - code examples for documentation where needed  
 - make list of refactoring / enhancements by writing TODO and FIXME in code 
 
For docstrings we use <https://google.github.io/styleguide/pyguide.html#Comments>. 

For testing we use py.test and make follwoing kinds of tests depending on situation:
 - unit tests:
   - a dumb tests with no control values to make sure a method is callable (like for ```__repr__()```), 
   - unit test with simple control values for a small fucntion / method, ususally public ones 
 - behaviour tests with fixtures / mocks for larger functionalities
 - end-to-end test on sample or real data  

Finished work example: **kep.files**:
- code: <https://github.com/epogrebnyak/mini-kep/blob/master/src/kep/files.py>
- test: https://github.com/epogrebnyak/mini-kep/blob/master/src/kep/tests/test_files.py
- rst: <https://github.com/epogrebnyak/mini-kep/blob/master/doc/kep.files.rst>
- documentation: <http://mini-kep-docs.s3-website-eu-west-1.amazonaws.com/kep.files.html>


Must reference this #38 in #52
