### ISSUE TITLE
make new fixtures in csv2df tests 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#52]
This review is similar to #38.

**Comment by epogrebnyak** [comment]
48c4125e967365e450946e047258992e9650c56f sets new file structure in src/kep2 and reduces dependencies. everuthis is run by runner.py 

Naming reference is [mailman](http://bazaar.launchpad.net/~mailman-coders/mailman/3.0/files/head:/src/mailman/handlers/) and [BW style guide](https://barry.warsaw.us/software/STYLEGUIDE.txt) (most importantly ```__all__``` and 1 class per module).

Major TODO is restoring tests, but should be easier once the components are decoupled.

**Comment by epogrebnyak** [comment]
New file structure testing:
[ ] emitter.py
[x] helpers.py
[ ] label.py
[ ] parcer.py
[ ] reader.py
[ ] runner.py
[ ] specification.py
[ ] tests
[ ] util_row_splitter.py
[ ] validator.py

**Comment by epogrebnyak** [comment]
TODO: 
- [ ] check all csv2df/*.py modules have __all__ property.
- [ ] check methods/classes in __all__ are tested

**Comment by bakakaldsas** [comment]
"""__all__""" property in modules:
[ ] emitter.py
[ ] helpers.py
[ ] parcer.py
[ ] reader.py
[ ] runner.py
[ ] specification.py
[ ] util_label.py
[ ] util_row_splitter.py
[ ] validator.py

**Comment by bakakaldsas** [comment]
Tests exist (might not be implemented, skipped, etc...):
- emitter.py:
    - [x] ```Emitter```
- helpers.py
    - [x] ```PathHelper```
    - [x] ```DateHelper```
- parcer.py (to be renamed to parser.py)
    - [x] ```extract_tables```
- reader.py
    - [ ] ```Reader```
    - [x] ```open_csv```
- runner.py
    - [x] ```get_dataframes```
    - [ ] ```Vintage```
    - [ ] ```Collection```
- specification.py
    #TODO ```__all__```
- util_label.py
    - [x] make_label
    - [x] split_label
    - [x] extract_varname
    - [x] extract_unit
- util_row_splitter.py
    #TODO ```__all__```
- validator.py
    #TODO ```__all__```
