### ISSUE TITLE
transform GOV_ACCUM_* variables to levels

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#66]

**Comment by zarak** [comment]
- [ ] TODO (EP): change names of variables to GOV_ACCUM_something

- [ ] TODO-1: check - accumulate diff_dfm and diff_dfq and compare to  gov_dfm and gov_dfq

- [ ] TODO-2: suggest more checks

- [ ] TODO-3: replace old variables with new variables at dfa, dfq, dfm

- [ ] TODO-4: supress warning or change code: A value is trying to be set on a copy of a slice from a DataFrame

**Comment by epogrebnyak** [comment]
Some takeaways for this issue. 

We had a task to check incoming dfa, dfq, dfm. This task has stages of: 
- df-level primitives. like accum* function  
- setup test arguments for a single 'resolution' function
- get result for the setup 
- optionally calculate coverage

With this we did:
   a) write and test the primitives
   b) deciding what to check and prepare variables to be checked 
   c) setting up feed of tests, digestible by a resolution function 
   c) running a feed of checks to get a pass/fail result for the test suite 
   d) knowing 'coverage' of checks  - what was not tested? 


My lessons learned are: 
- primities are testable with unittests and simple input values
- good when you arrive to a common formula for the primitives (like accum(df1)-df2 < epsilon)
- primitives should be clearly separated from setup
- sacrifices had to be made not to test everything

In #66 df_transform() separating primitives from transform job is also important, but setting teh varnames was more definite - we exactly know want variables we transform. 

@Zarak, your comment is welcome!

We leave it to rest for a while before integrating to parsing validation procedure.

**Comment by epogrebnyak** [comment]
This comment should be taken for sister issue #61.
