### ISSUE TITLE
better look and structure for sphinx documentation

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#72]
Current documentation:

<http://mini-kep-parcer-for-rosstat-kep-publication.readthedocs.io/en/latest/>

Doc folder: 

<https://github.com/epogrebnyak/mini-kep/tree/master/doc>

Script to generate docs:

```ctx.run("sphinx-apidoc -efM -o doc src\csv2df *test_*")```
at [tasks.py](https://github.com/epogrebnyak/mini-kep/blob/master/tasks.py)

My idea of the docs is the follwoing:

1. documentation page shows intro.rst and glossary.rst for the project
     and links to src/*packages* folders:

    -  download
    -  word2csv (will rename, it is now called word)
    -  csv2df
    -  frontpage

The link is a module name, possibly followed by a short comment. Can this comment be a module docstring?

2. At csv2df page I want a listing of modules with their docstrings. In listing I would prefer to control order of  modules listed as:
    - helpers
    - specification 
    - reader
    - parcer
    - runner 
    - validator
    - util_label
    - util_row_splitter

Can this order be specified somewhere, eg __all__constant?

3. When clicking on module name like 'helpers' I get its documentation.
    
For this structure I need a new commnd to put at tasks.py + manual edit of some .rst files, apparently.

**Comment by dz0** [comment]
"util_label" is for now "label"

**Comment by epogrebnyak** [comment]
Sorry, unclear. What did you mean?

**Comment by epogrebnyak** [comment]
Follow-up notes
- [ ] need directives to insert func/mod/class references in docstrings
- [ ] all file handling must go to a level up to src.locations
- [ ] docstrings reqire review
- [ ] frontpage documentation omitted for now, code has errors.

**Comment by epogrebnyak** [comment]
As of now in documentation I have an issue with modules.rst file. In runtime I get an error message:
```
\mini-kep\doc\rst\modules.rst:: WARNING: document isn't included in any toctree
```
I'm not understanding why modules.rst needed at all? It this a default file to insert to index.rst? 

Does inserting it to index.rst allow for cross-references to other modules in docstrings in some magic way?

**Comment by epogrebnyak** [comment]
Closing in favour of more specific issues on documentation.
