### ISSUE TITLE
frontend: Broken cyrillic characters in src/frontend outputs

### ISSUE THREAD

**Issue by bakakaldsas** [epogrebnyak/mini-kep#75]
file: [mini-kep/src/frontpage/_latest.md](https://github.com/epogrebnyak/mini-kep/blob/master/src/frontpage/_latest.md)
displays broken characters:

![broken chars](https://user-images.githubusercontent.com/8508037/29779375-12cd2330-8c1b-11e7-8b2c-40d0d9721542.jpg)

**Comment by bakakaldsas** [comment]
So does [mini-kep/src/frontpage/markdown/_latest.md](https://github.com/epogrebnyak/mini-kep/blob/master/src/frontpage/markdown/_latest.md)

**Comment by epogrebnyak** [comment]
Thanks for spotting, this will be something to fix under #12

**Comment by epogrebnyak** [comment]
Closing for now with "revisit" label - to open after urgent tasks are complete.
