### ISSUE TITLE
REST API for mini-kep

### ISSUE THREAD

**Issue by auvipy** [epogrebnyak/mini-kep#79]
Will put a user case here for the API, to work on a solution. Sorry this takes long to describe.

**Comment by auvipy** [comment]
@epogrebnyak

**Comment by epogrebnyak** [comment]
API interface prototypeing will be at <https://github.com/epogrebnyak/mini-kep/blob/master/src/getter.py>, but for now the issue is on hold as there too many things to do with the parcing part yet.

**Comment by epogrebnyak** [comment]
TODO:
- [get_from_web()](https://github.com/epogrebnyak/mini-kep/blob/master/src/getter.py#L35) is min prototype for interface
- make calls for similar variables (eg. CPI) from quandl and FRED
- dig some code for that in previous repos
