### ISSUE TITLE
testing: test.csv2df.reader.open_csv()

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#91]
Some cleanup / excercise based on 'dirty' test by @bakakaldsas [here](https://github.com/epogrebnyak/mini-kep/pull/90/commits/450dbb64c8faacf2b4fe91c3dfed577b9a24feb9). Hope you don't mind me pulling this to issue, it should help coming to common testing style. It extends #24 in a way. 

There are two things to 'clean' in test structure and several option on how to test.

Test structure:
- test naming should be observed, as with rest of python classes. Suggested name is Test_open_csv(). Caps for test name, lowercase due to it is testing a function *open_csv*. It should not be all lowercase for testclass.
- the part like below showld bertter go to either [setup_method](https://docs.pytest.org/en/2.7.3/xunit_setup.html#class-level-setup-teardown) or a [separate fixture](https://docs.pytest.org/en/latest/fixture.html). As we are not using it outside the class can settle for setup method.

```
    from pathlib import Path
    class MockPath(type(Path())):
        def open(self, mode='r', buffering=-1, encoding=None, errors=None, newline=None):
            return "test"

    path_good = MockPath()
    path_bad = "This is not pathlib.Path, this is a string"
 ```

As for the test essence there are several things we can test: 

1. is open_csv() callable
2. can it open a file?
3. can it open a file and the contents of the file is right?

(3) is a bit out of reach of open_csv() as it maust just open and not necassarily be responsible for content. So lets concentrate on (1) and (2).

In brief, @bakakaldsas you are testing (1), but the test is kind of self-fulilling with MockPath you wrote. From standard library you can use ```unittest.mock.mock_open()``` in MockPath to avoid creating custom-made open() method.

As for (2) one can also create a temp file, pass it to csv_open(), close/dekete file in teardown. I use that in <https://github.com/epogrebnyak/mini-kep/blob/master/src/tests/test_finaliser_and_getter.py> (with ```tempfile``` package to get temp dir/ tempfile).

What I'm doing in further commits is changing the structure of the submitted test and providing some new versions as described above.

**Comment by epogrebnyak** [comment]
Eventually, the test with <https://docs.python.org/3/library/unittest.mock.html#mock-open> I did not finish it, it seems the function can digest any kinds of arguments.

The test with temp file in b141b15 is really preferred one: it is quicker to write and easier to maintain, ab allows to test for (3) functionality too. I think the original submitted test is a good excercise too, will keep oit for a while in repo.

**Comment by epogrebnyak** [comment]
@bakakaldsas, I need you final "yes, sure" kind of approval to close this 👍

**Comment by bakakaldsas** [comment]
Yes, this is definitelly better.

**Comment by bakakaldsas** [comment]
So for the sake of cleaner test file the multiple test cases should be removed only leaving the preferred version?

**Comment by epogrebnyak** [comment]
I think yes, keep just one version, the simplest one. I moved things
around in last few commits.

2 сент. 2017 г. 22:37 пользователь "bakakaldsas" <notifications@github.com>
написал:

So for the sake of cleaner test file the multiple test cases should be
removed only leaving the preferred version?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/epogrebnyak/mini-kep/issues/91#issuecomment-326765232>,
or mute the thread
