### ISSUE TITLE
False as default value

### ISSUE THREAD

**Issue by bakakaldsas** [epogrebnyak/mini-kep#98]
While this is low priority at least further development of code can be done taking this into account.
-

- In many places in code `False` is used for default value `None` would be safer in some cases:
__1.__ `bool` <-> `int` conversion:
      `int(False)` -> `0`
      `5 + False` -> `5`
      when:
      `int(None)` -> `TypeError`
      `5 + None` -> `TypeError`
__2.__ False in some cases leads to ambiguity in conversion to bool
      `bool(False)` -> `False`
      `bool(0)` -> `False`
      `bool("")` -> `False`
      `bool([])` -> `False`
 - Safer approach would be setting `None` as default value
    and in `if` statements check:
```  
if x in not None:
    do_things()
```
 I recommend refactoring to reduce ambiguity and improve code safety

**Comment by epogrebnyak** [comment]
Thanks for bringing that up, at some point I thought False is better for some reason, which is wrong. 

My thought we might need a lookup comnand in tasks.py to check for regex in files.

**Comment by bakakaldsas** [comment]
Another constantly visible inconsistency is creation of dictionaries:
__1.__ d = dict(a=1,b=2)
__2.__ d = {a:1, b:2}

**Comment by epogrebnyak** [comment]
The dictionaries I think either way is fine. 

Listing ```=False``` cases with ```invoke find =False``` on linux:
```
./src/csv2df/emitter.py:57:    def make(self, freq: str, x: float, period=False):
./src/csv2df/emitter.py:143:            dups = df[df.duplicated(keep=False)]
./src/csv2df/specification.py:161:    def append(self, varname, text, required_units, desc=False):
./src/csv2df/specification.py:280:    def __init__(self, scope=False, reader=False, units=False):
./src/csv2df/validator.py:36:               period=False,
./src/csv2df/validator.py:37:               value=False)
./src/csv2df/validator.py:54:    def __init__(self, dfa, dfq, dfm, checkpoints=False):
./src/download/download.py:59:    def download(self, force=False):
./src/images.py:39:                 auto_x=False, axis_on=True):
./src/images.py:87:                         auto_x=False, axis_on=False)
./src/word2csv/word.py:188:def folder_to_csv(folder, csv_filename=False):
./tasks.py:121:    result = ctx.run(cmd, hide=False, warn=True)
```

**Comment by bakakaldsas** [comment]
How about such case?
```
class DatapointMaker:
    """Factory to make dictionaries representing a datapoint."""

    def __init__(self, year, label):
        self.year = year
        self.label = label
        self.freq = False
        self.value = False
        self.period = False
```

**Comment by epogrebnyak** [comment]
As an author for me it hard to see what is wrong with it.

**Comment by bakakaldsas** [comment]
Default values are also *False*. Only difference is that they are assigned in body of the method.

**Comment by epogrebnyak** [comment]
Can make them ```None``` as you suggest, but better also make the check ```is not None```.

**Comment by bakakaldsas** [comment]
My point here is that listing ```=False``` will not catch all cases of default ```False``` usage.

**Comment by epogrebnyak** [comment]
That we can easily change, its just an example.

**Comment by epogrebnyak** [comment]
Can even insert a proper regex there

**Comment by bakakaldsas** [comment]
Yes. But this is not high priority issue.
Only that possible refactoring should be taken into account when developing code further.

**Comment by epogrebnyak** [comment]
That shoudl be a good rule to follow, a style lesson. I'm closing this with Revisit tag to allow focusing on critical path issues - want to keep nember of open issues to 3-5 ideally.
